export default {
  TEST_ACTION: "TEST_ACTION",
  CREATE_REVISION: "CREATE_REVISION",
  LOAD_ARRAY_BUFFER: "LOAD_ARRAY_BUFFER",
  SELECT_REVISION: "SELECT_REVISION",
  SET_TRANSITION_MODAL_OPEN: "SET_TRANSITION_MODAL_OPEN",
  SET_NEW_TRANSITION_MODAL_OPEN: "SET_NEW_TRANSITION_MODAL_OPEN",
  LOAD_INSTRUMENTS: "LOAD_INSTRUMENTS",
  SET_CURRENT_BRIDGE: "SET_CURRENT_BRIDGE",
  ADD_BLOCK: "ADD_BLOCK",
  ADD_TRACK: "ADD_TRACK",
  UPDATE_TRACK: "UPDATE_TRACK"
};
