export default {
    TEST_ACTION: "TEST_ACTION",
    CREATE_REVISION: "CREATE_REVISION",
    LOAD_ARRAY_BUFFER: "LOAD_ARRAY_BUFFER",
    SELECT_REVISION: "SELECT_REVISION",
    LOAD_INSTRUMENTS: "LOAD_INSTRUMENTS"
};
